import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./styles/globals.css";
import QueryClientProvider from "./providers/QueryClient.provider";
import { Toaster } from "react-hot-toast";
import { AnimatePresence } from "framer-motion";
import { UserProvider } from "./contexts/userContext";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
const montserrat = Montserrat({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${montserrat.className} antialiased`}
      >
        <Toaster position="bottom-right" />
        <QueryClientProvider>
          <UserProvider>
            <AnimatePresence mode="wait">{children}</AnimatePresence>
          </UserProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
